# Generated by Django 2.2.7 on 2019-11-26 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20191126_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 20, 59, 5, 696175), verbose_name='添加时间'),
        ),
    ]
