# Generated by Django 2.2.7 on 2019-11-26 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20191126_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 21, 25, 9, 442466), verbose_name='添加时间'),
        ),
    ]
